export const LEADERBOARD_DATA = [
  {
    rank: 1,
    id: "emp_1",
    name: "Maria Santos",
    spms: 49,
    appraisal: 49,
    score: 98,
    department: "Operations",
    position: "Senior Manager",
    wins: 3,
    trend: "up",
    trendAmount: 2,
    rating: "Outstanding",
  },
  {
    rank: 2,
    id: "emp_2",
    name: "Juan dela Cruz",
    spms: 48,
    appraisal: 47,
    score: 95,
    department: "Human Resources",
    position: "HR Specialist",
    wins: 1,
    trend: "up",
    trendAmount: 1,
    rating: "Excellent",
  },
  {
    rank: 3,
    id: "emp_3",
    name: "Ana Reyes",
    spms: 46,
    appraisal: 46,
    score: 92,
    department: "Finance",
    position: "Budget Analyst",
    wins: 2,
    trend: "down",
    trendAmount: 1,
    rating: "Excellent",
  },
  {
    rank: 4,
    id: "emp_4",
    name: "Carlo Mendoza",
    spms: 45,
    appraisal: 44,
    score: 89,
    department: "Information Technology",
    position: "Systems Developer",
    wins: 0,
    trend: "up",
    trendAmount: 3,
    rating: "Very Satisfactory",
  },
  {
    rank: 5,
    id: "emp_5",
    name: "Liza Gomez",
    spms: 44,
    appraisal: 43,
    score: 87,
    department: "Legal Affairs",
    position: "Legal Officer",
    wins: 0,
    trend: "down",
    trendAmount: 2,
    rating: "Very Satisfactory",
  },
  {
    rank: 6,
    id: "emp_6",
    name: "Rico Tan",
    spms: 43,
    appraisal: 42,
    score: 85,
    department: "Administration",
    position: "Admin Officer",
    wins: 0,
    trend: "up",
    trendAmount: 1,
    rating: "Satisfactory",
  },
  {
    rank: 7,
    id: "emp_7",
    name: "Grace Villanueva",
    spms: 42,
    appraisal: 41,
    score: 83,
    department: "Marketing",
    position: "Marketing Specialist",
    wins: 0,
    trend: "up",
    trendAmount: 1,
    rating: "Satisfactory",
  },
  {
    rank: 8,
    id: "emp_8",
    name: "Ben Uy",
    spms: 41,
    appraisal: 40,
    score: 81,
    department: "Procurement",
    position: "Procurement Officer",
    wins: 0,
    trend: "down",
    trendAmount: 1,
    rating: "Satisfactory",
  },
  {
    rank: 9,
    id: "emp_9",
    name: "Nora Castillo",
    spms: 40,
    appraisal: 39,
    score: 79,
    department: "Logistics",
    position: "Logistics Coordinator",
    wins: 0,
    trend: "up",
    trendAmount: 2,
    rating: "Satisfactory",
  },
  {
    rank: 10,
    id: "emp_10",
    name: "Dante Cruz",
    spms: 39,
    appraisal: 38,
    score: 77,
    department: "Engineering",
    position: "Project Engineer",
    wins: 0,
    trend: "down",
    trendAmount: 1,
    rating: "Satisfactory",
  },
];

export const RATING_CONFIG = {
  Outstanding: {
    bg: "bg-amber-50",
    text: "text-amber-800",
    border: "border-amber-200",
  },
  Excellent: {
    bg: "bg-blue-50",
    text: "text-blue-800",
    border: "border-blue-200",
  },
  "Very Satisfactory": {
    bg: "bg-emerald-50",
    text: "text-emerald-800",
    border: "border-emerald-200",
  },
  Satisfactory: {
    bg: "bg-gray-100",
    text: "text-gray-600",
    border: "border-gray-200",
  },
};

export const MONTH_YEAR = "May 2025";
