export const Members = [
  {
    id: 1,
    firstName: "Lucia",
    lastName: "Fernandez",
    role: "HR Director",
    department: "Human Resources",
    email: "lfernandez@govmail.com",
    avatar: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 2,
    firstName: "Miguel",
    lastName: "Ramos",
    role: "HR Manager",
    department: "Human Resources",
    email: "mramos@govmail.com",
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 3,
    firstName: "Ana",
    lastName: "Lopez",
    role: "Recruitment Officer",
    department: "Human Resources",
    email: "alopez@govmail.com",
    avatar: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: 4,
    firstName: "Carlos",
    lastName: "Santos",
    role: "Hiring Officer",
    department: "Human Resources",
    email: "csantos@govmail.com",
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: 5,
    firstName: "Maria",
    lastName: "Gomez",
    role: "Payroll Officer",
    department: "Human Resources",
    email: "mgomez@govmail.com",
    avatar: "https://randomuser.me/api/portraits/women/15.jpg",
  },
];
