export const QUALIFICATION_EDUCATION_OPTIONS = [
  "2 years Certificate in Dental Hygiene",
  "B.S. Degree + 12 units MA",
  "B.S. Degree + 18 units MA",
  "B.S. Degree + 6 units MA",
  "Bachelor of Laws",
  "Bachelor of Science in Nursing",
  "Bachelor of Science in Nursing with at least 9 units in management course at the graduate level",
  "Bachelor of Science in Radiologic Technology",
  "Bachelor of Sicence in Respiratory Therapy",
  "Bachelor's degree",
  "Bachelor's degree in Architecture",
  "Bachelor's degree in Commerce/Business Administration major in Accounting",
  "Bachelor's degree in Engineering relevant to the job",
  "Bachelor's degree in Library Science or Information Science or Bachelor of Science in Education/Arts Major in Library Science",
  "Bachelor's degree in Medical Technology or Bachelor of Science in Public Health",
  "Bachelor's degree in Occupational Therapy",
  "Bachelor's degree in Pharmacy",
  "Bachelor's degree in Social Work",
  "Bachelor's degree in tourism, business, law, economics, marketing, public administration or other related fields",
  "Bachelor's degree major in Nutrition, Dietetics or Community Nutrition",
  "Bachelor's degree preferably in any of the following: Operations Management (OM); Human Resource Management (HRM); Human Resource Development (HRD); and/or allied fields",
  "Bachelor's degree preferably in journalism, mass communication or any related course",
  "Bachelor's degree relevant to the job",
  "BS Degree + 24 units MA",
  "BS Legal Management, AB Paralegal Studies, Law, Political Science or other allied courses",
  "Completion of 2 years of studies in College (prior to 2018), OR Completion Grade 12/Senior High School (starting 2016)",
  "Completion of 2 years of studies in College (prior to 2018), OR Completion of Grade 12/Senior High School (starting 2016)",
  "Completion of 2 years of studies in College (prior to 2018), OR High School Graduate with relevant vocational/trade course (prior to 2018), OR Completion of Grade 12/Senior High School under Technical-Vocational-Livelihood Track, OR Completion of Grade 10/Junior High School with relevant vocational/trade course (TESDA NC II) (starting 2018)",
  "Completion of 2 years studies in College",
  "Completion of 2 years studies in College (prior to 2018), OR Completion of Grade 12/Senior High School (starting 2016)",
  "Completion of 2 years studies in college or high school graduate with relevant vocational/trade course",
  "Completion of a course of at least four (4) years leading to the degree or Bachelor of Science in Medical Technology or Bachelor of Science in Public Health",
  "Completion of relevant 2 years studies in College or Completion of relevant medical laboratory technician course",
  "Completion of the Midwifery Course",
  "Doctor of Dental Medicine or Dental Surgery",
  "Doctor of Medicine",
  "Doctor of Veterinary Medicine",
  "Doctoral Degree",
  "Elementary School Graduate",
  "Elementary School Graduate or Completion of relevant vocational/trade course",
  "High School Graduate (prior to 2016) OR Completion of Grade 10/Junior High School (starting 2016)",
  "High School Graduate (prior to 2016), OR Completion of Grade 10/Junior High School (starting 2016) OR Completion of relevant vocational/trade course",
  "High School Graduate (prior to 2016), OR Completion of Grade 10/Junior High School (starting 2016), OR Completion of relevant vocational/trade course",
  "High School Graduate or Completion of relevant vocational/trade course",
  "High school graduate or completion of relevant/vocational course",
  "High school graduate or completion of relevant/vocational trade course",
  "MA",
  "MA + 18 units Doctorate",
  "MA + 24 units Doctorate",
  "MA + 9 units Doctorate",
  "MA + Doctoral Academic Units Completed",
  "Master's degree",
  "Master's degree in Guidance and Counselling",
  "Master's degree in Psychology",
  "Master's degree in tourism, business, economics, marketing, public administration or other related fields Or Bachelor of Laws",
  "Master's degree major in Nursing Service Administration preferably with units in PhD in Education pursuant to RA No. 9173 and DOH-NCHFD, HNSA Manual",
  "Master's degree major in Nursing Service Administration pursuant to RA No. 9173 and DOH-NCHFD, HNSA Manual",
  "Master's degree OR Certificate in Leadership and Management from the CSC",
  "Master's degree OR Certificate of Leadership and Management from the CSC",
  "Must be able to read and write",
];

export const QUALIFICATION_TRAINING_OPTIONS = [
  "15 hours of relevant training",
  "16 hours of relevant training",
  "16 hours of relevant training on DRRM",
  "16 hours of relevant training on employment facilitation",
  "16 hours of relevant training on the delivery of psychological services wthich include psychological interventions, psychological assessment and psychological programs*",
  "16 hours of training",
  "2 hours of relevant training on employment facilitation",
  "20 hours of relevant training",
  "24 hours of relevant training",
  "24 hours of training",
  "25 hours of relevant training",
  "28 hours of relevant training",
  "30 hours of relevant training",
  "32 hours of relevant training",
  "32 hours of supervisory/management learning and development intervention undertaken within the last five years With certificate as Level IV (Proficient) in DOH-NCP pursuant to DOH-DO No. 2012-0181; DOH-DM No. 2014-0074",
  "32 hours of training in management and supervision",
  "35 hours of relevant training",
  "4 hours of relevant training",
  "4 hours of relevant training on DRRM",
  "4 hours of relevant training on employment facilitation",
  "4 hours of relevant training on tourism",
  "4 hours of relevant training on tourism or ³DOT specific and mandatory trainings such as but not limited to the following: • Tourism Awareness and Capability Building Seminar for LGUs • Seminar on Disaster Risk Reduction and Management • Basic Tourism Statistics Training (BTST) • Local Tourism Guidebook Orientation and; • Seminar on Gender and Development Orientation",
  "4 hours of training",
  "4 hours of training relevant to legal work, such as legal ethics, legal research and writing, or legal procedure",
  "40 hours of relevant training",
  "40 hours of supervisory/management learning and development intervention",
  "45 hours of relevant training",
  "5 years of experience in a supervisory or managerial position in nursing with at least 2 years of experience in Nursing Service Administration",
  "8 hours of relevant training",
  "8 hours of relevant training on the delivery of psychological services wthich include psychological interventions, psychological assessment and psychological programs*",
  "8 hours of relevant training on tourism or ³DOT specific and mandatory trainings such as but not limited to the following: • Tourism Awareness and Capability Building Seminar for LGUs • Seminar on Disaster Risk Reduction and Management • Basic Tourism Statistics Training (BTST) Local Tourism Guidebook Orientation and; Seminar on Gender and Development Orientation",
  "8 hours of training",
  "8 hours of training on DRRM",
  "DOT specific and mandatory trainings such as but not limited to the following: • Tourism Awareness and Capability Building Seminar for LGUs • Seminar on Disaster Risk Reduction and Management • Basic Tourism Statistics Training (BTST) Local Tourism Guidebook Orientation and; Seminar on Gender and Development Orientation",
  "DOT specific and mandatory trainings such as but not limited to the following: • Tourism Awareness and Capability Building Seminar for LGUs • Seminar on Disaster Risk Reduction and Management • Basic Tourism Statistics Training (BTST) • Local Tourism Statistics Training (BTST) • Seminar on Gender and Development Orientation",
  "Eight (8) hours of training in radiologic technology with special modalities undertaken within the last five (5) years",
  "Four (4) hours of training in radiologic technology",
  "None",
  "None required",
];

export const QUALIFICATION_EXPERIENCE_OPTIONS = [
  "1 year of experience",
  "1 year of experience in program management relative to employment facilitation",
  "1 year of relevant experience",
  "1 year of relevant experience in the tourism industry either in the private sector of the government",
  "1 year of relevant experience involving the delivery of psychological services",
  "1 year of relevant experience on DRRM",
  "1 years of work experience and involvement in the tourism industry either in the private sector or the government",
  "2 years of experience",
  "2 years of relevant experience",
  "2 years of relevant experience + VS Performace Rating",
  "2 years of relevant experience involving the delivery of psychological services",
  "2 years of relevant experience on DRRM",
  "2 years of work experience and involvement in the tourism industry either in the private sector or the government",
  "3 years experience in general nursing service administration",
  "3 years experience in writing articles and researche papers or in writing for print, television or broadcast media",
  "3 years of experience",
  "3 years of experience in program management relative to employment facilitation",
  "3 years of relevant experience",
  "3 years of relevant experience + VS Performance Rating",
  "3 years of relevant experience on DRRM",
  "3 years of work experience and involvement in the tourism industry either in the private sector or the government",
  "4 years of experience",
  "4 years of experience in a supervisory or managerial position in nursing with at least 1 year of experience in Nursing Service Administration",
  "4 years of experience in a supervisory or managerial position in nursing, preferably with 1 year of experience in nursing education, training and research administration",
  "4 years of relevant experience",
  "4 years of relevant experience + VS Performance Rating",
  "4 years of supervisory/management experience",
  "4 years of work experience and involvement in the tourism industry either in the private sector or the government",
  "40 hours of supervisory/management learning and development intervention undertaken within the last five years in pursuant to CSC MC No. 05, s. 2016 With certificate as Level IV (Proficient) in DOH-NCP pursuant to DOH-Do No. 2012-0181; DOH-DM No. 2014-0074",
  "5 years in position/s involving management and supervision",
  "5 years of relevant experience + VS Performance Rating",
  "6 years of relevant experience + VS Performance Rating",
  "7 years of relevant experience + VS Performance Rating",
  "8 years of relevant experience + VS Performance Rating",
  "at least Five (5) years of relevant experience",
  "at least three (3) years of relevant experience",
  "None",
  "None required",
  "One (1) year of experience as a Radiologic Technologist",
  "Two (2) years of experience as a Radiologic Technologist",
];

export const QUALIFICATION_ELIGIBILITY_OPTIONS = [
  "Air-Conditioning/Refrigeration Technician (Category II)",
  "Audio Visual Equipment Operator/Technician (Category II)",
  "Career Service (Professional) Second Level Eligibility",
  "Career Service (Subprofessional) First Level Eligibility",
  "Carpenter (Category II)",
  "Communications Equipment Operator (Category II)",
  "Draftsman (Category II)",
  "Electrician (Category II)",
  "First Grade Civil Service Eligibility or its equivalent",
  "Heavy Equipment Operator (Category II)",
  "Illustrator (Category II)",
  "Laboratory Technician (Category II)",
  "Mechanic (Category II)",
  "Mechanical Equipment Operator (Category II)",
  "Medical Equipment Technician (Category II)",
  "Metal Worker (Category II)",
  "None required",
  "None required (Category III)",
  "None required; RA 1080 (for courses requiring BAR or BOARD eligibility)",
  "Painter (Category II)",
  "Photographer (Category II)",
  "Plumber (Category II)",
  "Professional Driver's License (Category IV)",
  "R.A. 1080",
  "R.A. 1080 (Architect)",
  "R.A. 1080 (BAR)",
  "R.A. 1080 (Certified Public Accountant)",
  "R.A. 1080 (Dental Hygienist)",
  "R.A. 1080 (Dentist)",
  "R.A. 1080 (Guidance Counselor)",
  "R.A. 1080 (Librarian)",
  "R.A. 1080 (Medical Laboratory Technician)",
  "R.A. 1080 (Medical Technologist)",
  "R.A. 1080 (Midwife)",
  "R.A. 1080 (Nurse)",
  "R.A. 1080 (Nutritionist-Dietitian)",
  "R.A. 1080 (Pharmacist)",
  "R.A. 1080 (Radiologic Technologist)",
  "R.A. 1080 (Social Worker)",
  "R.A. 1080 (Veterinarian)",
  "R.A. No. 10029 (Psychologist)",
  "RA 1080 (Respiratory Therapist)",
  "Security Guard License (Category IV)",
];

export const QUALIFICATION_COMPETENCY_OPTIONS = [
  "• Communication (Intermediate)",
  "• Creative and Innovative Thinking (Intermediate)",
  "• Management Information (Intermediate)",
  "• Personal Effectiveness (Intermediate)",
  "• Planning & Delivering (Intermediate)",
  "Core Competencies:\n• Exemplifying Ethics & Integrity (Basic)\n• Decision Making and Problem Solving (Basic)\n• Customer Focus/ Delivering Service Excellence (Basic)\nOrganizational Competencies:\n• Communication (Basic)\n• Personal Effectiveness (Basic)\n• Planning & Delivering (Basic)\n• Management Information (Basic)\n• Creative and Innovative Thinking (Basic)",
  "Core Competencies:\n• Exemplifying Ethics & Integrity (Intermediate)\n• Decision Making and Problem Solving (Intermediate)\n• Customer Focus/ Delivering Service Excellence (Intermediate)\nOrganizational Competencies:\n• Communication (Intermediate)\n• Personal Effectiveness (Intermediate)\n• Planning & Delivering (Intermediate)\n• Management Information (Intermediate)\n• Creative and Innovative Thinking (Intermediate)",
  "Core Competencies:\n• Exemplifying Ethics & Integrity (Advanced)\n• Decision Making and Problem Solving (Advanced)\n• Customer Focus/ Delivering Service Excellence (Advanced)\nLeadership Competencies:\n• Managing Performance (Advanced)\n• Building Commitment (Advanced)\n• Developing People (Advanced)\n• Partnering & Networking (Advanced)\n• Strategic Thinking (Advanced)\n• Leading Change/ Transformative Leadership (Advanced)\nOrganizational Competencies:\n• Communication (Advanced)\n• Personal Effectiveness (Advanced)\n• Planning & Delivering (Advanced)\n• Management Information (Advanced)\n• Creative and Innovative Thinking (Advanced)",
  "Core Competencies:\n• Exemplifying Ethics & Integrity (Superior)\n• Decision Making and Problem Solving (Superior)\n• Customer Focus/ Delivering Service Excellence (Superior)\nLeadership Competencies:\n• Managing Performance (Superior)\n• Building Commitment (Superior)\n• Developing People (Superior)\n• Partnering & Networking (Superior)\n• Strategic Thinking (Superior)\n• Leading Change/ Transformative Leadership (Superior)\nOrganizational Competencies:\n• Communication (Superior)\n• Personal Effectiveness (Superior)\n• Planning & Delivering (Superior)\n• Management Information (Superior)\n• Creative and Innovative Thinking (Superior)",
];
