export { LEAVE_TYPES } from "./leavePolicy";

export const STATUS_CONFIG = {
  approved: {
    label: "Approved",
    color: "text-emerald-700",
    bg: "bg-emerald-50",
    border: "border-emerald-200",
    dot: "bg-emerald-500",
  },
  pending: {
    label: "Pending",
    color: "text-amber-700",
    bg: "bg-amber-50",
    border: "border-amber-200",
    dot: "bg-amber-500",
  },
  rejected: {
    label: "Rejected",
    color: "text-red-700",
    bg: "bg-red-50",
    border: "border-red-200",
    dot: "bg-red-500",
  },
};

export const DEPARTMENTS = [
  "Engineering",
  "Product",
  "Design",
  "Marketing",
  "Sales",
  "HR",
  "Finance",
  "Operations",
];

export const EMPLOYEES = [
  {
    id: "e1",
    name: "Sophia Chen",
    avatar: null,
    department: "Engineering",
    designation: "Senior Engineer",
    managerId: "e5",
    email: "sophia.chen@company.com",
  },
  {
    id: "e2",
    name: "Marcus Williams",
    avatar: null,
    department: "Product",
    designation: "Product Manager",
    managerId: "e6",
    email: "marcus.w@company.com",
  },
  {
    id: "e3",
    name: "Priya Patel",
    avatar: null,
    department: "Design",
    designation: "UI/UX Lead",
    managerId: "e6",
    email: "priya.p@company.com",
  },
  {
    id: "e4",
    name: "James O'Brien",
    avatar: null,
    department: "Engineering",
    designation: "Backend Developer",
    managerId: "e5",
    email: "james.o@company.com",
  },
  {
    id: "e5",
    name: "Elena Vasquez",
    avatar: null,
    department: "Engineering",
    designation: "Engineering Manager",
    managerId: null,
    email: "elena.v@company.com",
  },
  {
    id: "e6",
    name: "David Kim",
    avatar: null,
    department: "Product",
    designation: "VP Product",
    managerId: null,
    email: "david.k@company.com",
  },
  {
    id: "e7",
    name: "Aisha Nkrumah",
    avatar: null,
    department: "Marketing",
    designation: "Marketing Lead",
    managerId: null,
    email: "aisha.n@company.com",
  },
  {
    id: "e8",
    name: "Ryan Torres",
    avatar: null,
    department: "Sales",
    designation: "Sales Executive",
    managerId: null,
    email: "ryan.t@company.com",
  },
];

export const CURRENT_USER = EMPLOYEES[0];

export const LEAVE_REQUESTS = [
  {
    id: "lr1",
    employeeId: "e1",
    employeeName: "Sophia Chen",
    department: "Engineering",
    leaveType: "vacation",
    startDate: "2025-06-10",
    endDate: "2025-06-14",
    days: 5,
    reason: "Family vacation to the mountains. Long planned trip.",
    status: "approved",
    appliedDate: "2025-05-20",
    approverId: "e5",
    approverName: "Elena Vasquez",
    remarks: "Approved. Enjoy your trip!",
    halfDay: false,
  },
  {
    id: "lr2",
    employeeId: "e2",
    employeeName: "Marcus Williams",
    department: "Product",
    leaveType: "sick",
    startDate: "2025-05-28",
    endDate: "2025-05-29",
    days: 2,
    reason: "Fever and cold. Doctor advised rest.",
    status: "approved",
    appliedDate: "2025-05-27",
    approverId: "e6",
    approverName: "David Kim",
    remarks: "Get well soon!",
    halfDay: false,
  },
  {
    id: "lr3",
    employeeId: "e3",
    employeeName: "Priya Patel",
    department: "Design",
    leaveType: "vacation",
    startDate: "2025-06-20",
    endDate: "2025-06-25",
    days: 6,
    reason: "Annual family gathering abroad.",
    status: "pending",
    appliedDate: "2025-05-21",
    approverId: "e6",
    approverName: "David Kim",
    remarks: null,
    halfDay: false,
  },
  {
    id: "lr4",
    employeeId: "e4",
    employeeName: "James O'Brien",
    department: "Engineering",
    leaveType: "emergency",
    startDate: "2025-05-22",
    endDate: "2025-05-23",
    days: 2,
    reason: "Family emergency requiring immediate attention.",
    status: "approved",
    appliedDate: "2025-05-22",
    approverId: "e5",
    approverName: "Elena Vasquez",
    remarks: "Take care.",
    halfDay: false,
  },
  {
    id: "lr5",
    employeeId: "e7",
    employeeName: "Aisha Nkrumah",
    department: "Marketing",
    leaveType: "maternity",
    startDate: "2025-07-01",
    endDate: "2025-09-30",
    days: 91,
    reason: "Maternity leave - expected delivery date June 28.",
    status: "approved",
    appliedDate: "2025-05-15",
    approverId: "e5",
    approverName: "Elena Vasquez",
    remarks: "Congratulations! All the best.",
    halfDay: false,
  },
  {
    id: "lr6",
    employeeId: "e8",
    employeeName: "Ryan Torres",
    department: "Sales",
    leaveType: "vacation",
    startDate: "2025-06-01",
    endDate: "2025-06-05",
    days: 5,
    reason: "Personal travel plans.",
    status: "rejected",
    appliedDate: "2025-05-18",
    approverId: "e6",
    approverName: "David Kim",
    remarks: "Cannot be approved due to critical quarter-end activities.",
    halfDay: false,
  },
  {
    id: "lr7",
    employeeId: "e1",
    employeeName: "Sophia Chen",
    department: "Engineering",
    leaveType: "sick",
    startDate: "2025-04-10",
    endDate: "2025-04-10",
    days: 1,
    reason: "Not feeling well - migraine.",
    status: "approved",
    appliedDate: "2025-04-10",
    approverId: "e5",
    approverName: "Elena Vasquez",
    remarks: null,
    halfDay: false,
  },
  {
    id: "lr8",
    employeeId: "e2",
    employeeName: "Marcus Williams",
    department: "Product",
    leaveType: "vacation",
    startDate: "2025-07-14",
    endDate: "2025-07-18",
    days: 5,
    reason: "Summer vacation with family.",
    status: "pending",
    appliedDate: "2025-05-21",
    approverId: "e6",
    approverName: "David Kim",
    remarks: null,
    halfDay: false,
  },
  {
    id: "lr9",
    employeeId: "e3",
    employeeName: "Priya Patel",
    department: "Design",
    leaveType: "sick",
    startDate: "2025-03-15",
    endDate: "2025-03-16",
    days: 2,
    reason: "Stomach flu.",
    status: "approved",
    appliedDate: "2025-03-15",
    approverId: "e6",
    approverName: "David Kim",
    remarks: "Feel better.",
    halfDay: false,
  },
  {
    id: "lr10",
    employeeId: "e4",
    employeeName: "James O'Brien",
    department: "Engineering",
    leaveType: "unpaid",
    startDate: "2025-08-01",
    endDate: "2025-08-07",
    days: 7,
    reason: "Personal time off for a sabbatical project.",
    status: "pending",
    appliedDate: "2025-05-21",
    approverId: "e5",
    approverName: "Elena Vasquez",
    remarks: null,
    halfDay: false,
  },
];

export const LEAVE_BALANCES = [
  {
    employeeId: "e1",
    vacation: { total: 21, used: 5, carryForward: 3 },
    sick: { total: 15, used: 1, carryForward: 0 },
    emergency: { total: 5, used: 0, carryForward: 0 },
    maternity: { total: 0, used: 0, carryForward: 0 },
    paternity: { total: 5, used: 0, carryForward: 0 },
    unpaid: { total: 999, used: 0, carryForward: 0 },
  },
  {
    employeeId: "e2",
    vacation: { total: 21, used: 7, carryForward: 2 },
    sick: { total: 15, used: 2, carryForward: 0 },
    emergency: { total: 5, used: 0, carryForward: 0 },
    maternity: { total: 0, used: 0, carryForward: 0 },
    paternity: { total: 5, used: 0, carryForward: 0 },
    unpaid: { total: 999, used: 0, carryForward: 0 },
  },
  {
    employeeId: "e3",
    vacation: { total: 21, used: 6, carryForward: 5 },
    sick: { total: 15, used: 2, carryForward: 0 },
    emergency: { total: 5, used: 1, carryForward: 0 },
    maternity: { total: 90, used: 0, carryForward: 0 },
    paternity: { total: 0, used: 0, carryForward: 0 },
    unpaid: { total: 999, used: 0, carryForward: 0 },
  },
];

export const HOLIDAYS = [
  { id: "h1", name: "New Year's Day", date: "2025-01-01", type: "public" },
  { id: "h2", name: "Independence Day", date: "2025-07-04", type: "public" },
  { id: "h3", name: "Labor Day", date: "2025-09-01", type: "public" },
  { id: "h4", name: "Thanksgiving", date: "2025-11-27", type: "public" },
  { id: "h5", name: "Christmas Day", date: "2025-12-25", type: "public" },
  {
    id: "h6",
    name: "Company Foundation Day",
    date: "2025-06-15",
    type: "company",
  },
  { id: "h7", name: "Founders Day", date: "2025-10-10", type: "company" },
];

export const MONTHLY_TRENDS = [
  { month: "Jan", vacation: 8, sick: 12, emergency: 2, other: 1 },
  { month: "Feb", vacation: 5, sick: 18, emergency: 1, other: 2 },
  { month: "Mar", vacation: 10, sick: 8, emergency: 3, other: 1 },
  { month: "Apr", vacation: 14, sick: 6, emergency: 2, other: 3 },
  { month: "May", vacation: 20, sick: 5, emergency: 4, other: 2 },
  { month: "Jun", vacation: 32, sick: 4, emergency: 1, other: 1 },
  { month: "Jul", vacation: 28, sick: 7, emergency: 2, other: 2 },
  { month: "Aug", vacation: 25, sick: 9, emergency: 3, other: 1 },
  { month: "Sep", vacation: 18, sick: 11, emergency: 2, other: 2 },
  { month: "Oct", vacation: 12, sick: 14, emergency: 1, other: 1 },
  { month: "Nov", vacation: 9, sick: 16, emergency: 2, other: 3 },
  { month: "Dec", vacation: 22, sick: 8, emergency: 1, other: 2 },
];

export const DEPT_USAGE = [
  { dept: "Engineering", days: 45 },
  { dept: "Product", days: 32 },
  { dept: "Design", days: 28 },
  { dept: "Marketing", days: 38 },
  { dept: "Sales", days: 22 },
  { dept: "HR", days: 15 },
  { dept: "Finance", days: 19 },
];

export const LEAVE_TYPE_PIE = [
  { name: "Vacation", value: 32, color: "#3b82f6" },
  { name: "Sick", value: 22, color: "#f59e0b" },
  { name: "Maternity", value: 10, color: "#ec4899" },
  { name: "Paternity", value: 6, color: "#8b5cf6" },
  { name: "Special Privilege", value: 8, color: "#06b6d4" },
  { name: "Calamity", value: 5, color: "#64748b" },
  { name: "Other", value: 17, color: "#6366f1" },
];

export const NOTIFICATIONS = [
  {
    id: "n1",
    type: "approved",
    message: "Your vacation leave request has been approved",
    time: "2 min ago",
    read: false,
  },
  {
    id: "n2",
    type: "pending",
    message: "New leave request from Priya Patel awaiting approval",
    time: "1 hour ago",
    read: false,
  },
  {
    id: "n3",
    type: "reminder",
    message: "3 pending leave requests require your action",
    time: "3 hours ago",
    read: true,
  },
  {
    id: "n4",
    type: "rejected",
    message: "Leave request by Ryan Torres has been rejected",
    time: "Yesterday",
    read: true,
  },
  {
    id: "n5",
    type: "approved",
    message: "James O'Brien emergency leave approved",
    time: "Yesterday",
    read: true,
  },
];

export const ACTIVITIES = [
  {
    id: "a1",
    employee: "Elena Vasquez",
    action: "approved",
    target: "Sophia Chen's vacation leave",
    time: "5 min ago",
    type: "approved",
  },
  {
    id: "a2",
    employee: "Priya Patel",
    action: "submitted",
    target: "a vacation leave request",
    time: "1 hour ago",
    type: "pending",
  },
  {
    id: "a3",
    employee: "David Kim",
    action: "rejected",
    target: "Ryan Torres's vacation request",
    time: "3 hours ago",
    type: "rejected",
  },
  {
    id: "a4",
    employee: "James O'Brien",
    action: "submitted",
    target: "an emergency leave request",
    time: "5 hours ago",
    type: "pending",
  },
  {
    id: "a5",
    employee: "Elena Vasquez",
    action: "approved",
    target: "Aisha Nkrumah's maternity leave",
    time: "Yesterday",
    type: "approved",
  },
];
